-- Query 1
SELECT T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT,
	COUNT(A.CUSTOMER_ID) AS APPOINTMENT_COUNT
FROM T_APPOINTMENT A
RIGHT JOIN
	(SELECT B.ID AS BIODATA_ID,
			B.FULLNAME AS FULLNAME,
			C.ID AS ID,
	 		C.DOB AS DOB,
			CASE
				WHEN DATE_PART('YEAR', AGE(NOW(), C.DOB)) > 0 THEN CAST(DATE_PART('YEAR', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Tahun'
				ELSE CAST(DATE_PART('MONTH', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Bulan'
			END AS AGE,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
	 		BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME AS RELATION,
			COUNT(CC.CUSTOMER_ID) AS CHAT_COUNT,
	 		B.IS_DELETE
		FROM M_BIODATA B
		INNER JOIN M_CUSTOMER C ON B.ID = C.BIODATA_ID
	 	INNER JOIN M_BLOOD_GROUP BG ON BG.ID = C.BLOOD_GROUP_ID
		INNER JOIN M_CUSTOMER_MEMBER CM ON C.ID = CM.CUSTOMER_ID
		INNER JOIN M_CUSTOMER_RELATION CR ON CR.ID = CM.CUSTOMER_RELATION_ID
		LEFT JOIN T_CUSTOMER_CHAT CC ON C.ID = CC.CUSTOMER_ID
		WHERE CM.PARENT_BIODATA_ID = 1
		GROUP BY B.ID,
			B.FULLNAME,
			C.ID,
	 		C.DOB,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
		 	BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME,	
			B.IS_DELETE) T1 ON T1.ID = A.CUSTOMER_ID
WHERE T1.IS_DELETE = FALSE
GROUP BY T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT;

SELECT C.*, COUNT(CC.CUSTOMER_ID) AS CHAT_COUNT
FROM M_CUSTOMER C
INNER JOIN T_CUSTOMER_CHAT CC
	ON C.ID = CC.CUSTOMER_ID
GROUP BY C.*

-- Query 2 = Query 1 + Fitur Search
SELECT T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT,
	COUNT(A.CUSTOMER_ID) AS APPOINTMENT_COUNT
FROM T_APPOINTMENT A
RIGHT JOIN
	(SELECT B.ID AS BIODATA_ID,
			B.FULLNAME AS FULLNAME,
			C.ID AS ID,
	 		C.DOB AS DOB,
			CASE
				WHEN DATE_PART('YEAR', AGE(NOW(), C.DOB)) > 0 THEN CAST(DATE_PART('YEAR', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Tahun'
				ELSE CAST(DATE_PART('MONTH', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Bulan'
			END AS AGE,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
	 		BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME AS RELATION,
			COUNT(CC.CUSTOMER_ID) AS CHAT_COUNT,
	 		B.IS_DELETE
		FROM M_BIODATA B
		INNER JOIN M_CUSTOMER C ON B.ID = C.BIODATA_ID
	 	INNER JOIN M_BLOOD_GROUP BG ON BG.ID = C.BLOOD_GROUP_ID
		INNER JOIN M_CUSTOMER_MEMBER CM ON C.ID = CM.CUSTOMER_ID
		INNER JOIN M_CUSTOMER_RELATION CR ON CR.ID = CM.CUSTOMER_RELATION_ID
		LEFT JOIN T_CUSTOMER_CHAT CC ON C.ID = CC.CUSTOMER_ID
		WHERE CM.PARENT_BIODATA_ID = 1
		GROUP BY B.ID,
			B.FULLNAME,
			C.ID,
	 		C.DOB,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
		 	BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME,	
			B.IS_DELETE) T1 ON T1.ID = A.CUSTOMER_ID
WHERE fullname ilike '%sa%' AND T1.IS_DELETE = FALSE
GROUP BY T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT;

-- Query 3 = Query 2 + Pagination
SELECT T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT,
	COUNT(A.CUSTOMER_ID) AS APPOINTMENT_COUNT
FROM T_APPOINTMENT A
RIGHT JOIN
	(SELECT B.ID AS BIODATA_ID,
			B.FULLNAME AS FULLNAME,
			C.ID AS ID,
	 		C.DOB AS DOB,
			CASE
				WHEN DATE_PART('YEAR', AGE(NOW(), C.DOB)) > 0 THEN CAST(DATE_PART('YEAR', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Tahun'
				ELSE CAST(DATE_PART('MONTH', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Bulan'
			END AS AGE,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
	 		BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME AS RELATION,
			COUNT(CC.CUSTOMER_ID) AS CHAT_COUNT,
	 		B.IS_DELETE
		FROM M_BIODATA B
		INNER JOIN M_CUSTOMER C ON B.ID = C.BIODATA_ID
	 	INNER JOIN M_BLOOD_GROUP BG ON BG.ID = C.BLOOD_GROUP_ID
		INNER JOIN M_CUSTOMER_MEMBER CM ON C.ID = CM.CUSTOMER_ID
		INNER JOIN M_CUSTOMER_RELATION CR ON CR.ID = CM.CUSTOMER_RELATION_ID
		LEFT JOIN T_CUSTOMER_CHAT CC ON C.ID = CC.CUSTOMER_ID
		WHERE CM.PARENT_BIODATA_ID = 1
		GROUP BY B.ID,
			B.FULLNAME,
			C.ID,
	 		C.DOB,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
		 	BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME,	
			B.IS_DELETE) T1 ON T1.ID = A.CUSTOMER_ID
WHERE fullname ilike '%%' AND T1.IS_DELETE = FALSE
GROUP BY T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT
ORDER BY T1.FULLNAME DESC
LIMIT 2 OFFSET 0;

-- Query Count Jumlah Data dengan keyword
SELECT 
	COUNT(T1.*) 
FROM (SELECT T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.RELATION,
	T1.AGE,
	T1.CHAT_COUNT,
	COUNT(A.CUSTOMER_ID) AS APPOINTMENT_COUNT,
	T1.IS_DELETE
FROM T_APPOINTMENT A
RIGHT JOIN
	(SELECT B.ID AS BIODATA_ID,
			B.FULLNAME AS FULLNAME,
			C.ID AS ID,
			CR.NAME AS RELATION,
			CASE
				WHEN DATE_PART('YEAR', AGE(NOW(), C.DOB)) > 0 THEN CAST(DATE_PART('YEAR', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Tahun'
				ELSE CAST(DATE_PART('MONTH', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Bulan'
			END AS AGE,
			COUNT(CC.CUSTOMER_ID) AS CHAT_COUNT,
	 		B.IS_DELETE
		FROM M_BIODATA B
		INNER JOIN M_CUSTOMER C ON B.ID = C.BIODATA_ID
		INNER JOIN M_CUSTOMER_MEMBER CM ON C.ID = CM.CUSTOMER_ID
		INNER JOIN M_CUSTOMER_RELATION CR ON CR.ID = CM.CUSTOMER_RELATION_ID
		LEFT JOIN T_CUSTOMER_CHAT CC ON C.ID = CC.CUSTOMER_ID
		WHERE CM.PARENT_BIODATA_ID = 1 AND B.IS_DELETE = FALSE
		GROUP BY B.ID,
			B.FULLNAME,
			C.ID,
			CR.NAME,	
			B.IS_DELETE) T1 ON T1.ID = A.CUSTOMER_ID
WHERE fullname ilike '%%'
GROUP BY T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.RELATION,
	T1.AGE,
	T1.CHAT_COUNT,
	T1.IS_DELETE) T1
-- limit 1 offset 0 1 2, limit 2 offset 0 2 4, limit 3 offset 0 3 6 9. 
-- Halaman 1 limit 2 offset 0, Halaman 2 limit 2 offset 2, Halaman 3 limit 2 offset 4
-- Offset Halaman 1 = 2 * (1-1)
-- Offset Halaman 2 = 2 * (2-1)
-- Offset Halaman 3 = 2 * (3-1)

SELECT * FROM m_user;
SELECT * FROM m_biodata;
SELECT * FROM m_customer;
SELECT * FROM m_customer_member;
SELECT * FROM m_customer_relation;
SELECT * FROM m_blood_group;

-- Add / Insert Fullname
INSERT INTO M_BIODATA (FULLNAME, CREATED_BY, CREATED_ON)
			   VALUES ('Saito Yasuda', 2, NOW()) RETURNING ID;
			   
-- Add / Insert DOB, Gender, Golongan Darah, Rhesus, Height, Weight
INSERT INTO M_CUSTOMER (BIODATA_ID, DOB, GENDER, BLOOD_GROUP_ID, RHESUS_TYPE, HEIGHT, WEIGHT, CREATED_BY, CREATED_ON)
				VALUES (10, '2021-12-25', 'L', 3, 'Rh +', CAST('75' AS DECIMAL), CAST('9' AS DECIMAL), 2, NOW()) RETURNING ID;

-- Add / Insert Relation
INSERT INTO M_CUSTOMER_MEMBER (CUSTOMER_ID, CUSTOMER_RELATION_ID, PARENT_BIODATA_ID, CREATED_BY, CREATED_ON)
					   VALUES (10, 5, 1, 2, NOW());
					   
-- Validasi Nama Lengkap Di Satu User / Customer;
SELECT EXISTS (SELECT * FROM M_BIODATA WHERE FULLNAME ilike 'Saito Haruka');
SELECT EXISTS (SELECT * FROM M_BIODATA WHERE FULLNAME ilike 'Saito Asuka' AND ID != 1);
SELECT ID FROM M_BIODATA WHERE FULLNAME ilike 'Saito Asuka';
SELECT EXISTS (SELECT * FROM M_CUSTOMER WHERE BIODATA_ID = 1);
SELECT ID FROM M_CUSTOMER WHERE BIODATA_ID = 1;
SELECT EXISTS (SELECT * FROM M_CUSTOMER_MEMBER WHERE CUSTOMER_ID = 1 AND PARENT_BIODATA_ID = 1);

-- Update Fullname
UPDATE M_BIODATA
SET FULLNAME = 'Saito Yamada',
	MODIFIED_BY = 2,
	MODIFIED_ON = NOW()
WHERE ID = 11;
			   
-- Update DOB, Gender, Golongan Darah, Rhesus, Height, Weight
UPDATE M_CUSTOMER
SET DOB = '2021-12-25',
	GENDER = 'L',
	BLOOD_GROUP_ID = 3,
	RHESUS_TYPE = 'Rh +',
	HEIGHT = 75,
	WEIGHT = 9,
	MODIFIED_BY = 2,
	MODIFIED_ON = NOW()
WHERE ID = 10;

-- Update Relation
UPDATE M_CUSTOMER_MEMBER
SET CUSTOMER_RELATION_ID = 3,
	MODIFIED_BY = 2,
	MODIFIED_ON = NOW()
WHERE CUSTOMER_ID = 10
	AND PARENT_BIODATA_ID = 1;
	
-- Query Single DELETE Pasien
UPDATE M_CUSTOMER_MEMBER SET
	IS_DELETE = TRUE,
	DELETED_BY = 2,
	DELETED_ON = NOW()
WHERE CUSTOMER_ID = 4;

UPDATE M_CUSTOMER SET
	IS_DELETE = TRUE,
	DELETED_BY = 2,
	DELETED_ON = NOW()
WHERE ID = 4 RETURNING BIODATA_ID;

UPDATE M_BIODATA SET
	IS_DELETE = TRUE,
	DELETED_BY = 2,
	DELETED_ON = NOW()
WHERE ID = 4;

-- Query Multiple DELETE Pasien
UPDATE M_CUSTOMER_MEMBER SET
	IS_DELETE = TRUE,
	DELETED_BY = 2,
	DELETED_ON = NOW()
WHERE CUSTOMER_ID IN (4,5);

UPDATE M_CUSTOMER SET
	IS_DELETE = TRUE,
	DELETED_BY = 2,
	DELETED_ON = NOW()
WHERE ID IN (4,5) RETURNING BIODATA_ID;

UPDATE M_BIODATA SET
	IS_DELETE = TRUE,
	DELETED_BY = 2,
	DELETED_ON = NOW()
WHERE ID IN (4,5);

-- Query ngambil nama untuk ditampilkan di multiple delete
SELECT B.ID AS BIODATA_ID,
	B.FULLNAME,
	C.ID AS CUSTOMER_ID
FROM M_BIODATA B
INNER JOIN M_CUSTOMER C ON B.ID = C.BIODATA_ID
WHERE C.ID IN (4,5);

-- Coba
SELECT T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT,
	COUNT(A.CUSTOMER_ID) AS APPOINTMENT_COUNT
FROM T_APPOINTMENT A
RIGHT JOIN
	(SELECT B.ID AS BIODATA_ID,
			B.FULLNAME AS FULLNAME,
			C.ID AS ID,
	 		C.DOB AS DOB,
			CASE
				WHEN DATE_PART('YEAR', AGE(NOW(), C.DOB)) > 0 THEN CAST(DATE_PART('YEAR', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Tahun'
				ELSE CAST(DATE_PART('MONTH', AGE(NOW(), C.DOB)) AS TEXT) || ' ' || 'Bulan'
			END AS AGE,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
	 		BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME AS RELATION,
			COUNT(CC.CUSTOMER_ID) AS CHAT_COUNT,
	 		B.IS_DELETE
		FROM M_BIODATA B
		INNER JOIN M_CUSTOMER C ON B.ID = C.BIODATA_ID
	 	INNER JOIN M_BLOOD_GROUP BG ON BG.ID = C.BLOOD_GROUP_ID
		INNER JOIN M_CUSTOMER_MEMBER CM ON C.ID = CM.CUSTOMER_ID
		INNER JOIN M_CUSTOMER_RELATION CR ON CR.ID = CM.CUSTOMER_RELATION_ID
		LEFT JOIN T_CUSTOMER_CHAT CC ON C.ID = CC.CUSTOMER_ID
		WHERE CM.PARENT_BIODATA_ID = 1
		GROUP BY B.ID,
			B.FULLNAME,
			C.ID,
	 		C.DOB,
	 		C.GENDER,
			C.BLOOD_GROUP_ID,
		 	BG.CODE,
			C.RHESUS_TYPE,
			C.HEIGHT,
			C.WEIGHT,
	 		CM.CUSTOMER_RELATION_ID,
			CR.NAME,	
			B.IS_DELETE) T1 ON T1.ID = A.CUSTOMER_ID
WHERE fullname ilike '%%' AND T1.IS_DELETE = FALSE
GROUP BY T1.BIODATA_ID,
	T1.FULLNAME,
	T1.ID,
	T1.DOB,
	T1.AGE,
	T1.GENDER,
	T1.BLOOD_GROUP_ID,
	T1.CODE,
	T1.RHESUS_TYPE,
	T1.HEIGHT,
	T1.WEIGHT,
	T1.CUSTOMER_RELATION_ID,
	T1.RELATION,
	T1.CHAT_COUNT
ORDER BY CHAT_COUNT ASC
LIMIT 3 OFFSET 0;